### ISSUE TITLE
Run through a linter like solhint

### ISSUE THREAD

**Issue by jacob-eliosoff** [alexroan/USM#13]
My first stab (like, never heard of solhint before 30 min ago) didn't turn up anything too horrifying:

![image](https://user-images.githubusercontent.com/8806519/92767920-96794d80-f365-11ea-9637-20fc224fc1f9.png)

**Comment by albertocuestacanada** [comment]
Cool! Can you make this into a PR?

**Comment by jacob-eliosoff** [comment]
Well, yeah the changes are easy, I'm just not 100% on most of them...  What is the correct visibility of a const like `WAD`, public?  Is it safe to rename Migration.sol's `last_completed_migration` to `lastCompletedMigration`?  Do we really need to shorten those USM error messages?  I could try but I'd be guessing a bit...

**Comment by albertocuestacanada** [comment]
For now you can always use `public` for variables. Better to not touch `Migrations.sol` - good chance to check how to exclude lines or files for Solhint.

**Comment by albertocuestacanada** [comment]
But if you do a PR, I can fix whichever errors you are not sure about.

**Comment by jacob-eliosoff** [comment]
OK I will!

**Comment by jacob-eliosoff** [comment]
See #14...  My first time creating a branch for a PR, hopefully don't bork anything

**Comment by alexroan** [comment]
No Borks 😄
